### ISSUE TITLE
14.0 Current: author's primary signature expired

### ISSUE THREAD

**Issue by Slesa** [sec/dotnet-core-freebsd-source-build#3] opened 2021-09-27 20:25 UTC
When calling build_runtime.sh, I get the nuget error

```
error NU3037: Package 'Microsoft.SourceLink.Common from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json': The author primary signature validity period has expired.
```

for different packages.

**Comment by sec** [comment] 2021-09-27 21:09
Hm, please try `pkg install ca_root_nss` as root and let me know if this helps.

**Comment by Slesa** [comment] 2021-09-27 21:15
Unfortunately not: The most recent versions of packages are already installed

**Comment by sec** [comment] 2021-09-27 21:27
This looks like certificate issue of some kind - give me few mins I will setup 14 on VM and check :)

**Comment by sec** [comment] 2021-09-27 22:23
I can confirm that under 14-CURRENT, didn't hit that under 12 nor 13, so I have really no idea what changed in 14 that could trigger this. I will try to dig into this and fix it somehow - if you cn you can try to build under 12 or 13 - that should work :)

**Comment by Slesa** [comment] 2021-09-28 10:07
This is true. I am compiling w/o problems on GhostBSD, which means 13.0 stable. So, could it be a change in ca_root_nss?

**Comment by arrowd** [comment] 2021-09-28 10:44
I bumped into the same problem when I was playing with dotnet/installer. Also FreeBSD 14, inside the jail.

**Comment by arrowd** [comment] 2021-09-28 10:49
Interestingly, both `fetch` and `curl` can successfully fetch that `index.json` file, which means that the certificates are fine. There is something inside the file, which confuses .NET.

**Comment by sec** [comment] 2021-09-28 10:59
> This is true. I am compiling w/o problems on GhostBSD, which means 13.0 stable. So, could it be a change in ca_root_nss? Edit: sorry for the stupid question, but how can I install th SDK from the tgz?

Just extract :) there will be `dotnet` binary inside with all the SDK's

**Comment by Slesa** [comment] 2021-10-07 22:27
I have no idea how to turnoff the signature validation :/ And I really do not understand how this can happen on 14-Currrent only - has the signature expired or not? 
There should be a command
```
nuget trusted-signers sync
```
may that could help?

**Comment by sec** [comment] 2021-10-11 07:51
Does this mean that pkgs.dev.azure.com is using nontrusted cert?

**Comment by sec** [comment] 2021-10-15 14:25
How did you run `nuget restore` ?

**Comment by Slesa** [comment] 2021-10-15 16:08
Sorry, dotnet restore

**Comment by sec** [comment] 2021-10-18 11:00
You want to compile the SDK yourself or just want to use SDK? If you want to just use SDK, then just extract it somewhere, add this directory to PATH (so that you have dotnet available) and you can use it like `dotnet new` etc. main branch is right now w.i.p. for rc-2. For rc-1 use the proper tag. Are you getting `author's primary signature expired` when trying to `dotnet restore` on some of your projects or when trying to compile the SDK from sources (this error I'm also getting with new ca_root_nss package and have no idea how to fix that atm).

**Comment by sec** [comment] 2022-01-28 16:56
Closing this, as:
- there is a workaround provided in README
- it's fixed now by https://github.com/NuGet/NuGet.Client/pull/4389 and should no longer be an issue

**Closed by sec** 2022-01-28 16:56 UTC

**Comment by Thefrank** [comment] 2022-01-28 19:35
Footnote to the above mentioned PR: it might be a while before that actual makes it into an SDK. 6.0.3xx looks like the earliest it will be in.
